development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>  
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>  
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>  
      options:
        server_selection_timeout: 5
